[package]
name = "incus-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
http-client-unix-domain-socket = "0.1.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
